name: Build Python bindings

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 6 * * 1' # Run every monday at 06:00 UTC

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ['x86_64-unknown-linux-gnu', 'aarch64-unknown-linux-gnu']
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        manylinux: auto
        target: ${{ matrix.target }}
        command: build
        args: --release --no-sdist

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: build
        args: --release --no-sdist

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install aarch64-apple-darwin toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: build
        args: --release --no-sdist --universal2
