name: Publish Python bindings

on:
  release:
    types: [created]

jobs:
  # linux:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       target: ['x86_64-unknown-linux-gnu', 'aarch64-unknown-linux-gnu']
  #     fail-fast: false
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: messense/maturin-action@v1
  #     with:
  #       maturin-version: latest
  #       manylinux: auto
  #       target: ${{ matrix.target }}
  #       command: publish
  #       args: --no-sdist -u hledoux -p ${{ secrets.PASSWORD_PYPI }}

  win-p38:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: publish
        args: --no-sdist -u hledoux -p ${{ secrets.PASSWORD_PYPI }} -i python3.8

  win-p39:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: publish
        args: --no-sdist -u hledoux -p ${{ secrets.PASSWORD_PYPI }} -i python3.9

  win-p310:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: publish
        args: --no-sdist -u hledoux -p ${{ secrets.PASSWORD_PYPI }} -i python3.10


  macos-p38:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install aarch64-apple-darwin toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: publish
        args: --no-sdist --universal2 -u hledoux -p ${{ secrets.PASSWORD_PYPI }} -i python3.8

  macos-p39:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install aarch64-apple-darwin toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: publish
        args: --no-sdist --universal2 -u hledoux -p ${{ secrets.PASSWORD_PYPI }} -i python3.9

  macos-p310:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install aarch64-apple-darwin toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: publish
        args: --no-sdist --universal2 -u hledoux -p ${{ secrets.PASSWORD_PYPI }} -i python3.10        